### ISSUE TITLE
Chapitre 3 smart pointeur

### ISSUE THREAD

**Issue by nikolaspaci** [Laefy/CPP_Learning#6]
Bonjour,
Je voudrais remercier pour votre cours qui est extrêmement instructif et facilement compréhensible grâce aux nombreux exemples. 
Je voulais savoir pourquoi la partie détaillée sur les smart pointeurs a été enlevée du chapitre 3 sur le site (heureusement qu'il reste une trace dans le repo).
Merci :)

**Comment by Laefy** [comment]
Bonjour ! Ah merci, c'est très gentil 🙂
C'est parce qu'en terme de rythme, ca fait beaucoup d'un coup pour mes étudiants. Je vais reparler des smarts pointers (en tout cas, du unique_ptr), dans le chapitre 4 ou 5, une fois que je leur aurais expliqué les constructeurs de copie et de move.
